baseURL: 'https://nklsch.github.io'
languageCode: 'en-us'
title: 'Niklas Choinowski'
#theme: profiles

outputs:
  home:
    - 'HTML'
    - 'RSS'
    - 'JSON'
  page:
    - 'HTML'
    - 'RSS'

PagerSize: 3
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  useBootstrapCDN: fals
  animate: true

  theme:
    disableThemeToggle: true

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  navbar:
    align: ms-auto
    disableSearch: true
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: 'Hi, my name is'
    title: 'Niklas.'
    #subtitle: 'I build stuff'
    content: |
      I am a software developer with a strong interest in cybersecurity, holding a technical diploma in Computer Science and English. At present, I am a trainee Java developer at [develogment GmbH & Co. KG](https://www.develogment.com) in Kempen, NRW, Germany. 

      I am currently engaged in developing a Discord bot to assist administrators and moderators in managing their servers.
    image: /images/me.jpg
    bottomImage:
      enable: true
    roundImage: true
    button:
      enable: true
      name: 'Resume'
      url: '#'
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/nklsch
        - icon: fab fa-linkedin
          url: https://linkedin.com/in/nchoini

  # About
  about:
    enable: true
    title: 'About Me'
    image: '/images/me.jpg'
    content: |-
      Hi, I am Niklas. Since my childhood, I have been obsessed with computers—or more precisely, video games. After finding the most awesome game ever, Minecraft, I developed a strong interest in programming, and so my journey began. I learned Java and SQL in school and decided pretty fast, “That’s what I want to do.”

      As I grew older, my interests shifted slightly, and I also developed an interest in movies—especially an all-time classic when it comes to computers, The Matrix. Hacking became my biggest dream. During my late teenage years, I realized that hacking was a bit out of my league, so I started by analyzing my own systems for existing vulnerabilities and fixing them whenever possible.

      In 2024, I started my first cybersecurity certificate, the Cybersecurity Professional Certificate by Google, and earned it in January 2025. Soon, I will begin preparing for the CompTIA Security+ certification after I finish my apprenticeship. That’s all about me. My wish is to work in cybersecurity as an analyst because I’ve grown fond of this fascinating and rapidly changing field.

      Here are some of my Skills:
    programming_languages:
      enable: true
      title: '📌 Programming languages'
      items:
        - '[![Programming Languages](https://skillicons.dev/icons?i=js,java,cs,bash,nix,php)](https://skillicons.dev)'
    libs_frameworks:
      enable: true
      title: '📚 Libraries and Frameworks'
      items:
        - '[![Libraries and Frameworks](https://skillicons.dev/icons?i=nodejs,bootstrap)](https://skillicons.dev)'
    markup_style:
      enable: true
      title: '🎨 Markup and Style Languages'
      items:
        - '[![Markup and Style Languages](https://skillicons.dev/icons?i=html,css,markdown)](https://skillicons.dev)'
    devops:
      enable: true
      title: '🧠 DevOps'
      items:
        - '[![DevOps Tools](https://skillicons.dev/icons?i=docker,azure)](https://skillicons.dev)'
    databases:
      enable: true
      title: '🗄️ Databases'
      items:
        - '[![Databases](https://skillicons.dev/icons?i=mysql,postgres,sqlite)](https://skillicons.dev)'
    software_tools:
      enable: true
      title: '🔧 Software and Tools'
      items:
        - '[![Software and Tools](https://skillicons.dev/icons?i=git,github,neovim,linux,obsidian)](https://skillicons.dev)'

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: 'Trainee Java Developer'
        company: 'develogment GmbH & Co. KG'
        companyUrl: 'https://www.develogment.com'
        date: 'Aug 2022 - present'
        featuredLink:
          enable: false
          name: 'View the project'
          url: 'https://example.com'
        content: ''

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: 'Trade School'
        date: 2022-Present
        school:
          name: 'Berufskolleg Uerdingen'
          url: 'https://www.bkukr.de/'
        # Grade: '2.9 out of 6'
        featuredLink:
          enable: false
          url: 'https://example.com'
      - title: 'High School'
        date: 2014-2022
        school:
          name: 'Clara-Schumann-Gymnasium'
          url: 'https://clara-duelken.de/'
        Grade: '2.9 out of 6'
        content: 'Technical diploma in computer science and English.'
        featuredLink:
          enable: false
          url: 'https://example.com'

  # Achievements
  achievements:
    enable: true
    title: 'Certs'
    items:
      - title: 'Google Cybersecurity Professional Certificate'
        url: https://coursera.org/verify/professional-cert/ZC6JUM2ONP7I
        image: /images/certs/google-cybersecurity.png

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Proton Discord Bot
        content: A customizable Discord bot for server management.
        image: https://opengraph.githubassets.com/7fa70ab8da2623ca2a9ce4932f6745705c7e1e36f01d099f2ddd364935cbbbe1/Proton-Discord-Bot/Proton
        role: Lead Developer
        featured:
          name: Source
          link: https://github.com/Proton-Discord-Bot/Proton
        badges:
          - 'JavaScript'
          - 'SQL'
        links:
          # - icon: fa fa-envelope
          #   url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/Proton-Discord-Bot/Proton
      - title: NixOS Config
        content: My NixOS system config
        image: https://opengraph.githubassets.com/latest/nklsch/nixos-config
        role: Maintainer
        featured:
          name: Source
          link: https://github.com/NklsCh/nixos-config
        badges:
          - 'Nix'
          - 'Shell'
        links:

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: '
      Signal: v3rm1n.42<br>
      Matrix: @v3rm1n_:matrix.org<br>
      Discord: v3rm1n<br>
      '
    btnName: Mail me (Insecure)
    btnlink: 'mailto:niklas.choinowski@tuta.com'

    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    socialNetworks:
      github: https://github.com/nklsch
      linkedin: https://www.linkedin.com/in/nchoini/
      instagram: https://instagram.com/nkls.ch

  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: 'min read'
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: 'Read'
    toc: 'Table Of Contents'
    copyright: 'All rights reserved'
    pageNotFound: 'Page not found'
    emailText: 'Check out this site'

  datesFormat:
    article: 'Jan 2, 2006'
    articleList: 'Jan 2, 2006'
    articleRecent: 'Jan 2, 2006'

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
